[build]
  # Базовая директория для сборки
  base = "frontend"
  
  # Команда для сборки проекта (выполняется в папке frontend)
  command = "npm ci && npm run build"
  
  # Папка с результатом сборки (относительно frontend/)
  publish = "dist"
  
  # Node.js версия
  environment = { NODE_VERSION = "18" }

[build.processing]
  # Отключаем встроенную оптимизацию Netlify (у нас уже есть своя)
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Редиректы для SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Заголовки для кеширования статических файлов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Заголовки для сжатия
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Настройки для автодеплоя
[context.production]
  command = "npm ci && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run build"

[context.branch-deploy]
  command = "npm ci && npm run build"
