[build]
  base = "frontend"
  command = "npm ci --legacy-peer-deps --no-audit --no-fund && npm run build:android"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.17.0"
  NPM_VERSION = "10.8.2"
  NODE_ENV = "production"
  CI = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"
  GENERATE_SOURCEMAP = "false"
  VITE_SUPABASE_URL = "https://olutrxiazrmanrgzzwmb.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sdXRyeGlhenJtYW5yZ3p6d21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzMwMjEsImV4cCI6MjA2NjQ0OTAyMX0.qxU_1Fjk4Mu9vMSfEI4jSGm3yYhh9WbmlSEFttOMKiM"

# Redirect rules для SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Заголовки для безопасности и производительности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; frame-ancestors 'none';"
    # Принудительная загрузка ресурсов для Android
    X-Preload-Resources = "script,style"
    # Отключаем кеширование для HTML на мобильных
    Vary = "User-Agent"
    
# Заголовки для отладки и Android совместимости
[[headers]]
  for = "/index.html"
  [headers.values]
    X-Debug = "Netlify deployment"
    X-Timestamp = "2025-08-11"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    # Принудительная загрузка для Android
    X-Content-Type-Options = "nosniff"
    X-UA-Compatible = "IE=edge,chrome=1"

# Кеширование статических файлов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Сжатие для лучшей производительности
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Encoding = "gzip"

# Настройки для мобильных устройств
[[headers]]
  for = "/"
  [headers.values]
    X-UA-Compatible = "IE=edge"
    viewport = "width=device-width, initial-scale=1.0"
    # Специальная обработка для Android
    X-Android-Optimized = "true"
    
# Отключение кеширования для Android устройств
[[headers]]
  for = "/*"
  [headers.values.conditions]
    User-Agent = "*Android*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "Thu, 01 Jan 1970 00:00:00 GMT"
